# Generated by Django 3.1.2 on 2020-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.TextField()),
                ('gadget', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_name', models.TextField()),
                ('department_assets', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField(max_length=255)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_user', models.TextField(max_length=255)),
                ('asset_vendor', models.TextField(max_length=255)),
                ('asset_name', models.TextField(max_length=255)),
                ('asset_desc', models.TextField()),
                ('asset_model', models.TextField()),
                ('asset_image_url', models.URLField(max_length=2083)),
                ('asset_next_scheduled_maintenance', models.DateField()),
                ('asset_location', models.TextField()),
                ('asset_serial_no', models.TextField()),
            ],
        ),
    ]
