# Generated by Django 3.1.2 on 2020-10-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='staff_email_status',
            field=models.CharField(choices=[('functional', 'FUNCTIONAL'), ('deleted', 'DELETED'), ('suspended', 'SUSPENDED')], default='functional', max_length=16),
        ),
        migrations.AddField(
            model_name='inventorie',
            name='asset_status',
            field=models.CharField(choices=[('operational', 'OPERATIONAL'), ('need_upgrade', 'NEEDS UPGRADE'), ('faulty', 'FAULTY')], default='operational', max_length=16),
        ),
    ]
