# Generated by Django 3.1.2 on 2020-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20201010_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorie',
            name='asset_sub_location',
            field=models.CharField(choices=[('pharmacy', 'PHARMACY'), ('inventory', 'INVENTORY'), ('hmo', 'HMO'), ('mss_sales', 'STRATEGIC SALES'), ('mss_engineering', 'BIOMEDICAL ENGINEERING'), ('mss_bids_and_commercial', 'BIDS & COMMERCIAL'), ('mss_lab', 'MSS LAB'), ('mss_emerging_business', 'EMERGING BUSINESS'), ('mss_accounts', 'ACCOUNTS'), ('mss_projects', 'SPECIAL PROJECTS'), ('hr', 'HUMAN RESOURCES'), ('front_desk', 'FRONT DESK'), ('social_media', 'SOCIAL MEDIA'), ('logistic', 'DISPATCH AND DRIVERS'), ('facility', 'FACILITY')], default='mss_accounts', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventorie',
            name='asset_location',
            field=models.CharField(choices=[('ogudu', 'OGUDU'), ('ipaja', 'IPAJA'), ('adeniyi_jones', 'ADENIYI JONES')], default='ogudu', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventorie',
            name='asset_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorie',
            name='asset_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorie',
            name='asset_user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorie',
            name='asset_vendor',
            field=models.CharField(max_length=255),
        ),
    ]
