# Generated by Django 3.1.2 on 2020-10-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20201010_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventorie',
            new_name='Inventories',
        ),
    ]
