# Generated by Django 3.1.2 on 2020-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20201010_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='staff_email_status',
            field=models.CharField(choices=[('deleted', 'DELETED'), ('functional', 'FUNCTIONAL'), ('suspended', 'SUSPENDED')], default='functional', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='asset_location',
            field=models.CharField(choices=[('adeniyi_jones', 'ADENIYI JONES'), ('ogudu', 'OGUDU'), ('ipaja', 'IPAJA')], default='ogudu', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='asset_sub_location',
            field=models.CharField(choices=[('mss_accounts', 'ACCOUNTS'), ('mss_bids_and_commercial', 'BIDS & COMMERCIAL'), ('mss_engineering', 'BIOMEDICAL ENGINEERING'), ('logistic', 'DISPATCH AND DRIVERS'), ('mss_emerging_business', 'EMERGING BUSINESS'), ('facility', 'FACILITY'), ('front_desk', 'FRONT DESK'), ('hr', 'HUMAN RESOURCES'), ('hmo', 'HMO'), ('inventory', 'INVENTORY'), ('mss_lab', 'MSS LAB'), ('pharmacy', 'PHARMACY'), ('social_media', 'SOCIAL MEDIA'), ('mss_projects', 'SPECIAL PROJECTS'), ('mss_sales', 'STRATEGIC SALES')], default='mss_accounts', max_length=32),
        ),
    ]
