# Generated by Django 3.1.2 on 2020-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20201010_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='asset_next_scheduled_maintenance',
            new_name='next_maintenance',
        ),
    ]
