# Generated by Django 3.1.2 on 2020-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_auto_20201010_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='asset_serial_no',
            field=models.CharField(max_length=32),
        ),
    ]
