# Generated by Django 3.1.2 on 2020-10-10 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_remove_assigned_gadget_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_gadget',
            name='staff',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
