# Generated by Django 3.1.2 on 2020-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_assigned_gadget_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='asset_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
