# Generated by Django 3.1.2 on 2020-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_inventories_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='asset_location',
            field=models.CharField(choices=[('adeniyi_jones', 'ADENIYI JONES'), ('ogudu', 'OGUDU'), ('ipaja', 'IPAJA'), ('lasuth', 'LASUTH'), ('mcc', 'MCC'), ('vedic', 'VEDIC')], default='ogudu', max_length=16),
        ),
    ]
